version: '3.3'
services:
  web:
    image: php
    container_name: php-container
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    build:
      context: .
      dockerfile: dockerfile/Dockerfile-php
    restart: unless-stopped
  db:
    image: postgres:latest
    container_name: db
    hostname : db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    build:
      context: .
      dockerfile: dockerfile/Dockerfile-psql
    restart: unless-stopped

